const defaultState ={
    first_name: null,
    last_name: null,
    user_name: null,
    password: null,
    company: null,
    currentUserId: null,
    currentUser:null,
    displaylogin: false,
    tabvisible: false,
    overLay: false,
    FeedContent: '',
    feedFetch: false,
    currentOwner: null,
    showButton: true,
    showSwipeButtons: false,
    Update: false,
    FeedCommentId: null,
    createTask: '',
    overLayTask: false,
    loadingPg: true,
    searching: '',
    addIngredient: '',
    displayDate: false,
    dateTime: 0,
    status: '',
    quantity: '',
    currentUserObj: null,
    tasksArray:[]
   }
   export default defaultState;